[default]
# SECRET_KEY defined in the .secrets.toml file
ENVIRONMENT_NAME = 'default'  # Will be overide by the other environments
EXTENSIONS = [
    'src.flask_application.index.index:init_app'
]

[production]
ENVIRONMENT_NAME = 'production'

[development]
ENVIRONMENT_NAME = 'development'

[testing]
ENVIRONMENT_NAME = 'testing'
