SECRET_KEY = "1*srهسقञटىटठडثuyhd9руяksRعङचछشصw丹几尺NKoс5MMKjrxT;IEoскघजйQkc=Uaقىヨ尺己ثسzyuq/Wsиsठkiy/.lEg4LFQз,eOC9oगझ卂几尺ड&Ogسافلык<9x刀尺h2t57pP"
EXTENSIONS = [
    'extensions.client:init_app',
    'extensions.websocket:init_app',
    'blueprints.index:init_app',
    'blueprints.instalocker:init_app'
]
CHECK_CONNECTION = true

